//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: constraint.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The severity of an Alarm.
type Alarm_Severity int32

const (
	Alarm_INFO    Alarm_Severity = 0
	Alarm_WARNING Alarm_Severity = 1
	Alarm_SEVERE  Alarm_Severity = 2
	Alarm_UNKNOWN Alarm_Severity = 3
	Alarm_REFUSED Alarm_Severity = 4
)

// Enum value maps for Alarm_Severity.
var (
	Alarm_Severity_name = map[int32]string{
		0: "INFO",
		1: "WARNING",
		2: "SEVERE",
		3: "UNKNOWN",
		4: "REFUSED",
	}
	Alarm_Severity_value = map[string]int32{
		"INFO":    0,
		"WARNING": 1,
		"SEVERE":  2,
		"UNKNOWN": 3,
		"REFUSED": 4,
	}
)

func (x Alarm_Severity) Enum() *Alarm_Severity {
	p := new(Alarm_Severity)
	*p = x
	return p
}

func (x Alarm_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alarm_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[0].Descriptor()
}

func (Alarm_Severity) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[0]
}

func (x Alarm_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alarm_Severity.Descriptor instead.
func (Alarm_Severity) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0, 0}
}

type Constraint_ConstraintType int32

const (
	Constraint_UNDEFINED            Constraint_ConstraintType = 0
	Constraint_INT_RANGE            Constraint_ConstraintType = 2
	Constraint_FLOAT_RANGE          Constraint_ConstraintType = 4
	Constraint_INT_CHOICE           Constraint_ConstraintType = 5
	Constraint_STRING_CHOICE        Constraint_ConstraintType = 6
	Constraint_STRING_STRING_CHOICE Constraint_ConstraintType = 7
	Constraint_ALARM_TABLE          Constraint_ConstraintType = 8
)

// Enum value maps for Constraint_ConstraintType.
var (
	Constraint_ConstraintType_name = map[int32]string{
		0: "UNDEFINED",
		2: "INT_RANGE",
		4: "FLOAT_RANGE",
		5: "INT_CHOICE",
		6: "STRING_CHOICE",
		7: "STRING_STRING_CHOICE",
		8: "ALARM_TABLE",
	}
	Constraint_ConstraintType_value = map[string]int32{
		"UNDEFINED":            0,
		"INT_RANGE":            2,
		"FLOAT_RANGE":          4,
		"INT_CHOICE":           5,
		"STRING_CHOICE":        6,
		"STRING_STRING_CHOICE": 7,
		"ALARM_TABLE":          8,
	}
)

func (x Constraint_ConstraintType) Enum() *Constraint_ConstraintType {
	p := new(Constraint_ConstraintType)
	*p = x
	return p
}

func (x Constraint_ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constraint_ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[1].Descriptor()
}

func (Constraint_ConstraintType) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[1]
}

func (x Constraint_ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constraint_ConstraintType.Descriptor instead.
func (Constraint_ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{7, 0}
}

type Alarm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BitValue int32          `protobuf:"varint,1,opt,name=bit_value,json=bitValue,proto3" json:"bit_value,omitempty"` // range 0 to 31
	Severity Alarm_Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=st2138.Alarm_Severity" json:"severity,omitempty"`
	// Message to display in client GUI
	Description *PolyglotText `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *Alarm) GetBitValue() int32 {
	if x != nil {
		return x.BitValue
	}
	return 0
}

func (x *Alarm) GetSeverity() Alarm_Severity {
	if x != nil {
		return x.Severity
	}
	return Alarm_INFO
}

func (x *Alarm) GetDescription() *PolyglotText {
	if x != nil {
		return x.Description
	}
	return nil
}

// Alarm Table. Comprises a number of different Alarms.
type AlarmTableConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alarms []*Alarm `protobuf:"bytes,1,rep,name=alarms,proto3" json:"alarms,omitempty"`
}

func (x *AlarmTableConstraint) Reset() {
	*x = AlarmTableConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlarmTableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmTableConstraint) ProtoMessage() {}

func (x *AlarmTableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmTableConstraint.ProtoReflect.Descriptor instead.
func (*AlarmTableConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmTableConstraint) GetAlarms() []*Alarm {
	if x != nil {
		return x.Alarms
	}
	return nil
}

// Codes integers for display in client GUI as values or members of a pick list.
type Int32ChoiceConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choices []*Int32ChoiceConstraint_IntChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
}

func (x *Int32ChoiceConstraint) Reset() {
	*x = Int32ChoiceConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32ChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32ChoiceConstraint) ProtoMessage() {}

func (x *Int32ChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32ChoiceConstraint.ProtoReflect.Descriptor instead.
func (*Int32ChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{2}
}

func (x *Int32ChoiceConstraint) GetChoices() []*Int32ChoiceConstraint_IntChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// Range constraint including hard min & max values plus display min & max.
type Int32RangeConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinValue   int32 `protobuf:"varint,1,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue   int32 `protobuf:"varint,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Step       int32 `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	DisplayMin int32 `protobuf:"varint,4,opt,name=display_min,json=displayMin,proto3" json:"display_min,omitempty"`
	DisplayMax int32 `protobuf:"varint,5,opt,name=display_max,json=displayMax,proto3" json:"display_max,omitempty"`
}

func (x *Int32RangeConstraint) Reset() {
	*x = Int32RangeConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32RangeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32RangeConstraint) ProtoMessage() {}

func (x *Int32RangeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32RangeConstraint.ProtoReflect.Descriptor instead.
func (*Int32RangeConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{3}
}

func (x *Int32RangeConstraint) GetMinValue() int32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *Int32RangeConstraint) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Int32RangeConstraint) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *Int32RangeConstraint) GetDisplayMin() int32 {
	if x != nil {
		return x.DisplayMin
	}
	return 0
}

func (x *Int32RangeConstraint) GetDisplayMax() int32 {
	if x != nil {
		return x.DisplayMax
	}
	return 0
}

// Range constraint with hard min & max plus display min & max.
type FloatRangeConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinValue   float32 `protobuf:"fixed32,1,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue   float32 `protobuf:"fixed32,2,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	Step       float32 `protobuf:"fixed32,3,opt,name=step,proto3" json:"step,omitempty"`
	DisplayMin float32 `protobuf:"fixed32,4,opt,name=display_min,json=displayMin,proto3" json:"display_min,omitempty"`
	DisplayMax float32 `protobuf:"fixed32,5,opt,name=display_max,json=displayMax,proto3" json:"display_max,omitempty"`
}

func (x *FloatRangeConstraint) Reset() {
	*x = FloatRangeConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatRangeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatRangeConstraint) ProtoMessage() {}

func (x *FloatRangeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatRangeConstraint.ProtoReflect.Descriptor instead.
func (*FloatRangeConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{4}
}

func (x *FloatRangeConstraint) GetMinValue() float32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *FloatRangeConstraint) GetMaxValue() float32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *FloatRangeConstraint) GetStep() float32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *FloatRangeConstraint) GetDisplayMin() float32 {
	if x != nil {
		return x.DisplayMin
	}
	return 0
}

func (x *FloatRangeConstraint) GetDisplayMax() float32 {
	if x != nil {
		return x.DisplayMax
	}
	return 0
}

// A selection of strings for client GUI to use in pick list and other GUI elements.
type StringChoiceConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choices []string `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	Strict  bool     `protobuf:"varint,2,opt,name=strict,proto3" json:"strict,omitempty"`
}

func (x *StringChoiceConstraint) Reset() {
	*x = StringChoiceConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringChoiceConstraint) ProtoMessage() {}

func (x *StringChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringChoiceConstraint.ProtoReflect.Descriptor instead.
func (*StringChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{5}
}

func (x *StringChoiceConstraint) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *StringChoiceConstraint) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// A selection of human-friendly strings to display in client GUI that are
// used to select a string intended for machine use.
type StringStringChoiceConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choices []*StringStringChoiceConstraint_StringStringChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	Strict  bool                                               `protobuf:"varint,2,opt,name=strict,proto3" json:"strict,omitempty"`
}

func (x *StringStringChoiceConstraint) Reset() {
	*x = StringStringChoiceConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringStringChoiceConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringChoiceConstraint) ProtoMessage() {}

func (x *StringStringChoiceConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringChoiceConstraint.ProtoReflect.Descriptor instead.
func (*StringStringChoiceConstraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{6}
}

func (x *StringStringChoiceConstraint) GetChoices() []*StringStringChoiceConstraint_StringStringChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *StringStringChoiceConstraint) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

type Constraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Constraint_ConstraintType `protobuf:"varint,1,opt,name=type,proto3,enum=st2138.Constraint_ConstraintType" json:"type,omitempty"`
	// Types that are assignable to Kind:
	//
	//	*Constraint_RefOid
	//	*Constraint_AlarmTable
	//	*Constraint_Int32Range
	//	*Constraint_Int32Choice
	//	*Constraint_FloatRange
	//	*Constraint_StringChoice
	//	*Constraint_StringStringChoice
	Kind isConstraint_Kind `protobuf_oneof:"kind"`
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{7}
}

func (x *Constraint) GetType() Constraint_ConstraintType {
	if x != nil {
		return x.Type
	}
	return Constraint_UNDEFINED
}

func (m *Constraint) GetKind() isConstraint_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Constraint) GetRefOid() string {
	if x, ok := x.GetKind().(*Constraint_RefOid); ok {
		return x.RefOid
	}
	return ""
}

func (x *Constraint) GetAlarmTable() *AlarmTableConstraint {
	if x, ok := x.GetKind().(*Constraint_AlarmTable); ok {
		return x.AlarmTable
	}
	return nil
}

func (x *Constraint) GetInt32Range() *Int32RangeConstraint {
	if x, ok := x.GetKind().(*Constraint_Int32Range); ok {
		return x.Int32Range
	}
	return nil
}

func (x *Constraint) GetInt32Choice() *Int32ChoiceConstraint {
	if x, ok := x.GetKind().(*Constraint_Int32Choice); ok {
		return x.Int32Choice
	}
	return nil
}

func (x *Constraint) GetFloatRange() *FloatRangeConstraint {
	if x, ok := x.GetKind().(*Constraint_FloatRange); ok {
		return x.FloatRange
	}
	return nil
}

func (x *Constraint) GetStringChoice() *StringChoiceConstraint {
	if x, ok := x.GetKind().(*Constraint_StringChoice); ok {
		return x.StringChoice
	}
	return nil
}

func (x *Constraint) GetStringStringChoice() *StringStringChoiceConstraint {
	if x, ok := x.GetKind().(*Constraint_StringStringChoice); ok {
		return x.StringStringChoice
	}
	return nil
}

type isConstraint_Kind interface {
	isConstraint_Kind()
}

type Constraint_RefOid struct {
	// A reference to a shared constraint defined in device.constraints
	RefOid string `protobuf:"bytes,2,opt,name=ref_oid,json=refOid,proto3,oneof"`
}

type Constraint_AlarmTable struct {
	// Int32 Constraints
	AlarmTable *AlarmTableConstraint `protobuf:"bytes,3,opt,name=alarm_table,json=alarmTable,proto3,oneof"`
}

type Constraint_Int32Range struct {
	Int32Range *Int32RangeConstraint `protobuf:"bytes,4,opt,name=int32_range,json=int32Range,proto3,oneof"`
}

type Constraint_Int32Choice struct {
	Int32Choice *Int32ChoiceConstraint `protobuf:"bytes,5,opt,name=int32_choice,json=int32Choice,proto3,oneof"`
}

type Constraint_FloatRange struct {
	// Float Constraints
	FloatRange *FloatRangeConstraint `protobuf:"bytes,6,opt,name=float_range,json=floatRange,proto3,oneof"`
}

type Constraint_StringChoice struct {
	// String Constraints
	StringChoice *StringChoiceConstraint `protobuf:"bytes,7,opt,name=string_choice,json=stringChoice,proto3,oneof"`
}

type Constraint_StringStringChoice struct {
	StringStringChoice *StringStringChoiceConstraint `protobuf:"bytes,8,opt,name=string_string_choice,json=stringStringChoice,proto3,oneof"`
}

func (*Constraint_RefOid) isConstraint_Kind() {}

func (*Constraint_AlarmTable) isConstraint_Kind() {}

func (*Constraint_Int32Range) isConstraint_Kind() {}

func (*Constraint_Int32Choice) isConstraint_Kind() {}

func (*Constraint_FloatRange) isConstraint_Kind() {}

func (*Constraint_StringChoice) isConstraint_Kind() {}

func (*Constraint_StringStringChoice) isConstraint_Kind() {}

type Int32ChoiceConstraint_IntChoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32         `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name  *PolyglotText `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Int32ChoiceConstraint_IntChoice) Reset() {
	*x = Int32ChoiceConstraint_IntChoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32ChoiceConstraint_IntChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32ChoiceConstraint_IntChoice) ProtoMessage() {}

func (x *Int32ChoiceConstraint_IntChoice) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32ChoiceConstraint_IntChoice.ProtoReflect.Descriptor instead.
func (*Int32ChoiceConstraint_IntChoice) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Int32ChoiceConstraint_IntChoice) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Int32ChoiceConstraint_IntChoice) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

type StringStringChoiceConstraint_StringStringChoice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string        `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Name  *PolyglotText `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StringStringChoiceConstraint_StringStringChoice) Reset() {
	*x = StringStringChoiceConstraint_StringStringChoice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringStringChoiceConstraint_StringStringChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStringChoiceConstraint_StringStringChoice) ProtoMessage() {}

func (x *StringStringChoiceConstraint_StringStringChoice) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStringChoiceConstraint_StringStringChoice.ProtoReflect.Descriptor instead.
func (*StringStringChoiceConstraint_StringStringChoice) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{6, 0}
}

func (x *StringStringChoiceConstraint_StringStringChoice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StringStringChoiceConstraint_StringStringChoice) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_constraint_proto protoreflect.FileDescriptor

var file_constraint_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x1a, 0x0e, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x05, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x41, 0x6c, 0x61,
	0x72, 0x6d, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76,
	0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32,
	0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a,
	0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e, 0x46,
	0x4f, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x56, 0x45, 0x52, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x46,
	0x55, 0x53, 0x45, 0x44, 0x10, 0x04, 0x22, 0x3d, 0x0a, 0x14, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x25,
	0x0a, 0x06, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x06, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x73, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12,
	0x41, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e,
	0x49, 0x6e, 0x74, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0xa6, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x61, 0x78, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x74, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x69, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x61, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4d, 0x61,
	0x78, 0x22, 0x4a, 0x0a, 0x16, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x22, 0xdf, 0x01,
	0x0a, 0x1c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x51,
	0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x37, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x1a, 0x54, 0x0a, 0x12, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x9e, 0x05, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x35,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x5f, 0x6f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x66, 0x4f, 0x69, 0x64,
	0x12, 0x3f, 0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x63, 0x68, 0x6f, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33,
	0x38, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x74,
	0x32, 0x31, 0x33, 0x38, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x45, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x58,
	0x0a, 0x14, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x12, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e,
	0x54, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x4c, 0x4f,
	0x41, 0x54, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e,
	0x54, 0x5f, 0x43, 0x48, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54,
	0x52, 0x49, 0x4e, 0x47, 0x5f, 0x43, 0x48, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x06, 0x12, 0x18, 0x0a,
	0x14, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x43,
	0x48, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x41, 0x52, 0x4d,
	0x5f, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x08, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x42, 0x2e, 0x0a, 0x16, 0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x42, 0x10, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x50, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constraint_proto_rawDescOnce sync.Once
	file_constraint_proto_rawDescData = file_constraint_proto_rawDesc
)

func file_constraint_proto_rawDescGZIP() []byte {
	file_constraint_proto_rawDescOnce.Do(func() {
		file_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(file_constraint_proto_rawDescData)
	})
	return file_constraint_proto_rawDescData
}

var file_constraint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_constraint_proto_goTypes = []interface{}{
	(Alarm_Severity)(0),                                     // 0: st2138.Alarm.Severity
	(Constraint_ConstraintType)(0),                          // 1: st2138.Constraint.ConstraintType
	(*Alarm)(nil),                                           // 2: st2138.Alarm
	(*AlarmTableConstraint)(nil),                            // 3: st2138.AlarmTableConstraint
	(*Int32ChoiceConstraint)(nil),                           // 4: st2138.Int32ChoiceConstraint
	(*Int32RangeConstraint)(nil),                            // 5: st2138.Int32RangeConstraint
	(*FloatRangeConstraint)(nil),                            // 6: st2138.FloatRangeConstraint
	(*StringChoiceConstraint)(nil),                          // 7: st2138.StringChoiceConstraint
	(*StringStringChoiceConstraint)(nil),                    // 8: st2138.StringStringChoiceConstraint
	(*Constraint)(nil),                                      // 9: st2138.Constraint
	(*Int32ChoiceConstraint_IntChoice)(nil),                 // 10: st2138.Int32ChoiceConstraint.IntChoice
	(*StringStringChoiceConstraint_StringStringChoice)(nil), // 11: st2138.StringStringChoiceConstraint.StringStringChoice
	(*PolyglotText)(nil),                                    // 12: st2138.PolyglotText
}
var file_constraint_proto_depIdxs = []int32{
	0,  // 0: st2138.Alarm.severity:type_name -> st2138.Alarm.Severity
	12, // 1: st2138.Alarm.description:type_name -> st2138.PolyglotText
	2,  // 2: st2138.AlarmTableConstraint.alarms:type_name -> st2138.Alarm
	10, // 3: st2138.Int32ChoiceConstraint.choices:type_name -> st2138.Int32ChoiceConstraint.IntChoice
	11, // 4: st2138.StringStringChoiceConstraint.choices:type_name -> st2138.StringStringChoiceConstraint.StringStringChoice
	1,  // 5: st2138.Constraint.type:type_name -> st2138.Constraint.ConstraintType
	3,  // 6: st2138.Constraint.alarm_table:type_name -> st2138.AlarmTableConstraint
	5,  // 7: st2138.Constraint.int32_range:type_name -> st2138.Int32RangeConstraint
	4,  // 8: st2138.Constraint.int32_choice:type_name -> st2138.Int32ChoiceConstraint
	6,  // 9: st2138.Constraint.float_range:type_name -> st2138.FloatRangeConstraint
	7,  // 10: st2138.Constraint.string_choice:type_name -> st2138.StringChoiceConstraint
	8,  // 11: st2138.Constraint.string_string_choice:type_name -> st2138.StringStringChoiceConstraint
	12, // 12: st2138.Int32ChoiceConstraint.IntChoice.name:type_name -> st2138.PolyglotText
	12, // 13: st2138.StringStringChoiceConstraint.StringStringChoice.name:type_name -> st2138.PolyglotText
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_constraint_proto_init() }
func file_constraint_proto_init() {
	if File_constraint_proto != nil {
		return
	}
	file_language_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_constraint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alarm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlarmTableConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32ChoiceConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32RangeConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FloatRangeConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringChoiceConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringStringChoiceConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Constraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32ChoiceConstraint_IntChoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringStringChoiceConstraint_StringStringChoice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_constraint_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Constraint_RefOid)(nil),
		(*Constraint_AlarmTable)(nil),
		(*Constraint_Int32Range)(nil),
		(*Constraint_Int32Choice)(nil),
		(*Constraint_FloatRange)(nil),
		(*Constraint_StringChoice)(nil),
		(*Constraint_StringStringChoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constraint_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constraint_proto_goTypes,
		DependencyIndexes: file_constraint_proto_depIdxs,
		EnumInfos:         file_constraint_proto_enumTypes,
		MessageInfos:      file_constraint_proto_msgTypes,
	}.Build()
	File_constraint_proto = out.File
	file_constraint_proto_rawDesc = nil
	file_constraint_proto_goTypes = nil
	file_constraint_proto_depIdxs = nil
}
