//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: language.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Language Pack
// A map of string identifiers, e.g. "greeting" to strings which are all
// in the same language.
type LanguagePack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                           // e.g. "Global Spanish"
	Words map[string]string `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // e.g. "greeting" -> "Hola"
}

func (x *LanguagePack) Reset() {
	*x = LanguagePack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagePack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagePack) ProtoMessage() {}

func (x *LanguagePack) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagePack.ProtoReflect.Descriptor instead.
func (*LanguagePack) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{0}
}

func (x *LanguagePack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LanguagePack) GetWords() map[string]string {
	if x != nil {
		return x.Words
	}
	return nil
}

// Language Packs
// A map of language identifiers to resource dictionaries or language packs
// for each language supported.
// The keys shall be patterned on those defined in
// https://www.mesaonline.org/language-metadata-table, e.g.
// "es" for Global Spanish.
// "es-CO" for Colombian Spanish.
// "pl" for Jezyk polski
type LanguagePacks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packs map[string]*LanguagePack `protobuf:"bytes,1,rep,name=packs,proto3" json:"packs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LanguagePacks) Reset() {
	*x = LanguagePacks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagePacks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagePacks) ProtoMessage() {}

func (x *LanguagePacks) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagePacks.ProtoReflect.Descriptor instead.
func (*LanguagePacks) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{1}
}

func (x *LanguagePacks) GetPacks() map[string]*LanguagePack {
	if x != nil {
		return x.Packs
	}
	return nil
}

// PolyglotText
// Text that a client can display in one of multiple languages.
// The different options can either be defined in-line for each
// instance of this message, or they can reference a LanguagePack.
//
// When defined in-line, the keys shall be patterned on those defined at
// https://www.mesaonline.org/language-metadata-table with "example"
// substituted by "catena".
//
// In-line definition example:
//
//	{
//	   "en": "Hello",   // global English
//	   "es": "Hola",    // global Spanish
//	   "fr": "Bonjour", // global French
//	   "en-CA": "Eh?",  // Canadian English
//	},
//
// LanguagePack referencing example:
//
//	{
//	   "$key": "greeting"
//	}
//
// And when defined by reference to a language pack the $key value
// is used to provide a look-up into the supported LanguagePack(s)
// e.g. $key = "greeting" could index to "Hello", "Hola" or "Bonjour"
// depending on which LanguagePack was active in the client.
type PolyglotText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayStrings map[string]string `protobuf:"bytes,1,rep,name=display_strings,json=displayStrings,proto3" json:"display_strings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // In-line language definition
}

func (x *PolyglotText) Reset() {
	*x = PolyglotText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolyglotText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolyglotText) ProtoMessage() {}

func (x *PolyglotText) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolyglotText.ProtoReflect.Descriptor instead.
func (*PolyglotText) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{2}
}

func (x *PolyglotText) GetDisplayStrings() map[string]string {
	if x != nil {
		return x.DisplayStrings
	}
	return nil
}

// AddLanguagePayload
// Used by a client to request that a device adds support for a language pack.
type AddLanguagePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot         uint32        `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	LanguagePack *LanguagePack `protobuf:"bytes,2,opt,name=language_pack,json=languagePack,proto3" json:"language_pack,omitempty"`
	Language     string        `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // e.g. "es" Global Spanish.
}

func (x *AddLanguagePayload) Reset() {
	*x = AddLanguagePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLanguagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLanguagePayload) ProtoMessage() {}

func (x *AddLanguagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLanguagePayload.ProtoReflect.Descriptor instead.
func (*AddLanguagePayload) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{3}
}

func (x *AddLanguagePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AddLanguagePayload) GetLanguagePack() *LanguagePack {
	if x != nil {
		return x.LanguagePack
	}
	return nil
}

func (x *AddLanguagePayload) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// LanguagePackRequestPayload
// Requests a language pack from the device.
type LanguagePackRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot     uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`        // Uniquely identifies the device at node scope.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // e.g. "es" Global Spanish.
}

func (x *LanguagePackRequestPayload) Reset() {
	*x = LanguagePackRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguagePackRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagePackRequestPayload) ProtoMessage() {}

func (x *LanguagePackRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagePackRequestPayload.ProtoReflect.Descriptor instead.
func (*LanguagePackRequestPayload) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{4}
}

func (x *LanguagePackRequestPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LanguagePackRequestPayload) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Language List
// The list of language tags that the device supports.
//
// e.g.
// [
//
//	"en",
//	"es",
//	"fr"
//
// ] // Support for English, Spanish & French
//
// e.g.
// [] // No multi-lingual support
type LanguageList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Languages []string `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
}

func (x *LanguageList) Reset() {
	*x = LanguageList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LanguageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageList) ProtoMessage() {}

func (x *LanguageList) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageList.ProtoReflect.Descriptor instead.
func (*LanguageList) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{5}
}

func (x *LanguageList) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

// *
// Slot
type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_language_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_language_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_language_proto_rawDescGZIP(), []int{6}
}

func (x *Slot) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

var File_language_proto protoreflect.FileDescriptor

var file_language_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x22, 0x93, 0x01, 0x0a, 0x0c, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a,
	0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61,
	0x63, 0x6b, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97,
	0x01, 0x0a, 0x0d, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x73,
	0x12, 0x36, 0x0a, 0x05, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x70, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0x4e, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38,
	0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa4, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x51, 0x0a, 0x0f, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c, 0x79,
	0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x41, 0x0a, 0x13,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x7f, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x50, 0x61, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x22, 0x4c, 0x0a, 0x1a, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x2c,
	0x0a, 0x0c, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x22, 0x1a, 0x0a, 0x04,
	0x53, 0x6c, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x42, 0x2a, 0x0a, 0x14, 0x63, 0x61, 0x74, 0x65,
	0x6e, 0x61, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x42, 0x0e, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x48, 0x01, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_language_proto_rawDescOnce sync.Once
	file_language_proto_rawDescData = file_language_proto_rawDesc
)

func file_language_proto_rawDescGZIP() []byte {
	file_language_proto_rawDescOnce.Do(func() {
		file_language_proto_rawDescData = protoimpl.X.CompressGZIP(file_language_proto_rawDescData)
	})
	return file_language_proto_rawDescData
}

var file_language_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_language_proto_goTypes = []interface{}{
	(*LanguagePack)(nil),               // 0: st2138.LanguagePack
	(*LanguagePacks)(nil),              // 1: st2138.LanguagePacks
	(*PolyglotText)(nil),               // 2: st2138.PolyglotText
	(*AddLanguagePayload)(nil),         // 3: st2138.AddLanguagePayload
	(*LanguagePackRequestPayload)(nil), // 4: st2138.LanguagePackRequestPayload
	(*LanguageList)(nil),               // 5: st2138.LanguageList
	(*Slot)(nil),                       // 6: st2138.Slot
	nil,                                // 7: st2138.LanguagePack.WordsEntry
	nil,                                // 8: st2138.LanguagePacks.PacksEntry
	nil,                                // 9: st2138.PolyglotText.DisplayStringsEntry
}
var file_language_proto_depIdxs = []int32{
	7, // 0: st2138.LanguagePack.words:type_name -> st2138.LanguagePack.WordsEntry
	8, // 1: st2138.LanguagePacks.packs:type_name -> st2138.LanguagePacks.PacksEntry
	9, // 2: st2138.PolyglotText.display_strings:type_name -> st2138.PolyglotText.DisplayStringsEntry
	0, // 3: st2138.AddLanguagePayload.language_pack:type_name -> st2138.LanguagePack
	0, // 4: st2138.LanguagePacks.PacksEntry.value:type_name -> st2138.LanguagePack
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_language_proto_init() }
func file_language_proto_init() {
	if File_language_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_language_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagePack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagePacks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolyglotText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLanguagePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguagePackRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LanguageList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_language_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_language_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_language_proto_goTypes,
		DependencyIndexes: file_language_proto_depIdxs,
		MessageInfos:      file_language_proto_msgTypes,
	}.Build()
	File_language_proto = out.File
	file_language_proto_rawDesc = nil
	file_language_proto_goTypes = nil
	file_language_proto_depIdxs = nil
}
