//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: param.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamType int32

const (
	ParamType_UNDEFINED            ParamType = 0
	ParamType_EMPTY                ParamType = 1
	ParamType_INT32                ParamType = 4
	ParamType_FLOAT32              ParamType = 6
	ParamType_STRING               ParamType = 7
	ParamType_STRUCT               ParamType = 10
	ParamType_STRUCT_VARIANT       ParamType = 11
	ParamType_INT32_ARRAY          ParamType = 14
	ParamType_FLOAT32_ARRAY        ParamType = 16
	ParamType_STRING_ARRAY         ParamType = 17
	ParamType_BINARY               ParamType = 18
	ParamType_STRUCT_ARRAY         ParamType = 32
	ParamType_STRUCT_VARIANT_ARRAY ParamType = 33
	ParamType_DATA                 ParamType = 50 // Used to allow commands to accept files
)

// Enum value maps for ParamType.
var (
	ParamType_name = map[int32]string{
		0:  "UNDEFINED",
		1:  "EMPTY",
		4:  "INT32",
		6:  "FLOAT32",
		7:  "STRING",
		10: "STRUCT",
		11: "STRUCT_VARIANT",
		14: "INT32_ARRAY",
		16: "FLOAT32_ARRAY",
		17: "STRING_ARRAY",
		18: "BINARY",
		32: "STRUCT_ARRAY",
		33: "STRUCT_VARIANT_ARRAY",
		50: "DATA",
	}
	ParamType_value = map[string]int32{
		"UNDEFINED":            0,
		"EMPTY":                1,
		"INT32":                4,
		"FLOAT32":              6,
		"STRING":               7,
		"STRUCT":               10,
		"STRUCT_VARIANT":       11,
		"INT32_ARRAY":          14,
		"FLOAT32_ARRAY":        16,
		"STRING_ARRAY":         17,
		"BINARY":               18,
		"STRUCT_ARRAY":         32,
		"STRUCT_VARIANT_ARRAY": 33,
		"DATA":                 50,
	}
)

func (x ParamType) Enum() *ParamType {
	p := new(ParamType)
	*p = x
	return p
}

func (x ParamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParamType) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[0].Descriptor()
}

func (ParamType) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[0]
}

func (x ParamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParamType.Descriptor instead.
func (ParamType) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{0}
}

type UndefinedValue int32

const (
	UndefinedValue_UNDEFINED_VALUE UndefinedValue = 0
)

// Enum value maps for UndefinedValue.
var (
	UndefinedValue_name = map[int32]string{
		0: "UNDEFINED_VALUE",
	}
	UndefinedValue_value = map[string]int32{
		"UNDEFINED_VALUE": 0,
	}
)

func (x UndefinedValue) Enum() *UndefinedValue {
	p := new(UndefinedValue)
	*p = x
	return p
}

func (x UndefinedValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UndefinedValue) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[1].Descriptor()
}

func (UndefinedValue) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[1]
}

func (x UndefinedValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UndefinedValue.Descriptor instead.
func (UndefinedValue) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1}
}

type DataPayload_PayloadEncoding int32

const (
	DataPayload_UNCOMPRESSED DataPayload_PayloadEncoding = 0
	DataPayload_GZIP         DataPayload_PayloadEncoding = 1
	DataPayload_DEFLATE      DataPayload_PayloadEncoding = 2
)

// Enum value maps for DataPayload_PayloadEncoding.
var (
	DataPayload_PayloadEncoding_name = map[int32]string{
		0: "UNCOMPRESSED",
		1: "GZIP",
		2: "DEFLATE",
	}
	DataPayload_PayloadEncoding_value = map[string]int32{
		"UNCOMPRESSED": 0,
		"GZIP":         1,
		"DEFLATE":      2,
	}
)

func (x DataPayload_PayloadEncoding) Enum() *DataPayload_PayloadEncoding {
	p := new(DataPayload_PayloadEncoding)
	*p = x
	return p
}

func (x DataPayload_PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPayload_PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[2].Descriptor()
}

func (DataPayload_PayloadEncoding) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[2]
}

func (x DataPayload_PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPayload_PayloadEncoding.Descriptor instead.
func (DataPayload_PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1, 0}
}

type ParamInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The parameter's OID
	Oid string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	// The parameter's name to display in a client GUI
	Name *PolyglotText `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The parameter's type
	Type ParamType `protobuf:"varint,3,opt,name=type,proto3,enum=st2138.ParamType" json:"type,omitempty"`
	// The OID of the template from which this parameter was created
	TemplateOid string `protobuf:"bytes,4,opt,name=template_oid,json=templateOid,proto3" json:"template_oid,omitempty"`
}

func (x *ParamInfo) Reset() {
	*x = ParamInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfo) ProtoMessage() {}

func (x *ParamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfo.ProtoReflect.Descriptor instead.
func (*ParamInfo) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{0}
}

func (x *ParamInfo) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ParamInfo) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ParamInfo) GetType() ParamType {
	if x != nil {
		return x.Type
	}
	return ParamType_UNDEFINED
}

func (x *ParamInfo) GetTemplateOid() string {
	if x != nil {
		return x.TemplateOid
	}
	return ""
}

// When streamed, only the payload field will be used after the first message.
type DataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata        map[string]string           `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //information about the payload to be interpreted by the client (e.g. mime-type, filename, etc.)
	Digest          []byte                      `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`                                                                                             // SHA-256 digest of the payload - used to verify the integrity of the payload
	PayloadEncoding DataPayload_PayloadEncoding `protobuf:"varint,3,opt,name=payload_encoding,json=payloadEncoding,proto3,enum=st2138.DataPayload_PayloadEncoding" json:"payload_encoding,omitempty"`
	// Types that are assignable to Kind:
	//
	//	*DataPayload_Url
	//	*DataPayload_Payload
	Kind isDataPayload_Kind `protobuf_oneof:"kind"`
}

func (x *DataPayload) Reset() {
	*x = DataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPayload) ProtoMessage() {}

func (x *DataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPayload.ProtoReflect.Descriptor instead.
func (*DataPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1}
}

func (x *DataPayload) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DataPayload) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *DataPayload) GetPayloadEncoding() DataPayload_PayloadEncoding {
	if x != nil {
		return x.PayloadEncoding
	}
	return DataPayload_UNCOMPRESSED
}

func (m *DataPayload) GetKind() isDataPayload_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *DataPayload) GetUrl() string {
	if x, ok := x.GetKind().(*DataPayload_Url); ok {
		return x.Url
	}
	return ""
}

func (x *DataPayload) GetPayload() []byte {
	if x, ok := x.GetKind().(*DataPayload_Payload); ok {
		return x.Payload
	}
	return nil
}

type isDataPayload_Kind interface {
	isDataPayload_Kind()
}

type DataPayload_Url struct {
	Url string `protobuf:"bytes,4,opt,name=url,proto3,oneof"` // URL containing data for the payload
}

type DataPayload_Payload struct {
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3,oneof"` // Data for the payload
}

func (*DataPayload_Url) isDataPayload_Kind() {}

func (*DataPayload_Payload) isDataPayload_Kind() {}

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// the parameter's name
	Name *PolyglotText `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the parameter's type
	Type ParamType `protobuf:"varint,2,opt,name=type,proto3,enum=st2138.ParamType" json:"type,omitempty"`
	// Read only flag. Clients shall style the param's widget as read only when true.
	ReadOnly bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	// Identifies the GUI elements to display and adjust the parameter value.
	Widget string `protobuf:"bytes,4,opt,name=widget,proto3" json:"widget,omitempty"`
	// For float params, how many digits to display
	Precision uint32 `protobuf:"varint,5,opt,name=precision,proto3" json:"precision,omitempty"`
	// The parameter's value
	Value *Value `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	// The constraint's on the parameters' value.
	// Can be a reference to a shared constraint or defined in-line.
	Constraint *Constraint `protobuf:"bytes,7,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// For string params, the maximum length of the string
	// @todo - is this really needed? The proto encoding of strings includes their length
	MaxLength uint32 `protobuf:"varint,8,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// For string array params, the total length of all the strings in the array.
	// @todo - is this really needed? doesn't proto give us this info?
	TotalLength uint32 `protobuf:"varint,9,opt,name=total_length,json=totalLength,proto3" json:"total_length,omitempty"`
	// Access scope
	// if not present, the parameter's access scope is that of its parent.
	// if not a child parameter, the access scope is the default for the device.
	AccessScope string `protobuf:"bytes,10,opt,name=access_scope,json=accessScope,proto3" json:"access_scope,omitempty"`
	// Additional properties to assist client
	ClientHints map[string]string `protobuf:"bytes,11,rep,name=client_hints,json=clientHints,proto3" json:"client_hints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If this is a STRUCT or STRUCT_ARRAY Param its sub-params are defined here.
	Params map[string]*Param `protobuf:"bytes,13,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Meaningful when this message is used as a command descriptor
	// true if the command provides a response when executed.
	Response bool `protobuf:"varint,14,opt,name=response,proto3" json:"response,omitempty"`
	// Optional additional information about the usage of the parameter
	Help *PolyglotText `protobuf:"bytes,15,opt,name=help,proto3" json:"help,omitempty"`
	// Import directive
	Import *Import `protobuf:"bytes,16,opt,name=import,proto3" json:"import,omitempty"`
	// Additional OIDs represented by this parameter - used to allow a client to locate a parameter that may have been moved or renamed.
	// The aliases must be fully-qualified.
	OidAliases []string `protobuf:"bytes,17,rep,name=oid_aliases,json=oidAliases,proto3" json:"oid_aliases,omitempty"`
	// When true, indicates that the parameter is part of the minimal set of parameters that should be reported by the device
	MinimalSet bool `protobuf:"varint,18,opt,name=minimal_set,json=minimalSet,proto3" json:"minimal_set,omitempty"`
	// When true, indicates that the parameter is stateless
	// design intent is to signal that values of stateless parameters are not worth persisting
	// and that the device should not be expected to remember them across reboots.
	// Good examples of stateless parameters are: device's current time, audio meters, etc.
	Stateless bool `protobuf:"varint,19,opt,name=stateless,proto3" json:"stateless,omitempty"`
	// The OID of the template from which this parameter was created
	TemplateOid string `protobuf:"bytes,20,opt,name=template_oid,json=templateOid,proto3" json:"template_oid,omitempty"`
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{2}
}

func (x *Param) GetName() *PolyglotText {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Param) GetType() ParamType {
	if x != nil {
		return x.Type
	}
	return ParamType_UNDEFINED
}

func (x *Param) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Param) GetWidget() string {
	if x != nil {
		return x.Widget
	}
	return ""
}

func (x *Param) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Param) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Param) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

func (x *Param) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *Param) GetTotalLength() uint32 {
	if x != nil {
		return x.TotalLength
	}
	return 0
}

func (x *Param) GetAccessScope() string {
	if x != nil {
		return x.AccessScope
	}
	return ""
}

func (x *Param) GetClientHints() map[string]string {
	if x != nil {
		return x.ClientHints
	}
	return nil
}

func (x *Param) GetParams() map[string]*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Param) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *Param) GetHelp() *PolyglotText {
	if x != nil {
		return x.Help
	}
	return nil
}

func (x *Param) GetImport() *Import {
	if x != nil {
		return x.Import
	}
	return nil
}

func (x *Param) GetOidAliases() []string {
	if x != nil {
		return x.OidAliases
	}
	return nil
}

func (x *Param) GetMinimalSet() bool {
	if x != nil {
		return x.MinimalSet
	}
	return false
}

func (x *Param) GetStateless() bool {
	if x != nil {
		return x.Stateless
	}
	return false
}

func (x *Param) GetTemplateOid() string {
	if x != nil {
		return x.TemplateOid
	}
	return ""
}

// A value that can be one of several types, even within the same array
// The type to apply is determined by the struct_variant_type field which must match one
// of the keys in the descriptor's params map
type StructVariantValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of the variant
	StructVariantType string `protobuf:"bytes,1,opt,name=struct_variant_type,json=structVariantType,proto3" json:"struct_variant_type,omitempty"`
	// The value of the variant
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StructVariantValue) Reset() {
	*x = StructVariantValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructVariantValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructVariantValue) ProtoMessage() {}

func (x *StructVariantValue) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructVariantValue.ProtoReflect.Descriptor instead.
func (*StructVariantValue) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{3}
}

func (x *StructVariantValue) GetStructVariantType() string {
	if x != nil {
		return x.StructVariantType
	}
	return ""
}

func (x *StructVariantValue) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// An array of Values, each of which can be one of several types defined in the
// descriptor's params map
type StructVariantList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StructVariants []*StructVariantValue `protobuf:"bytes,1,rep,name=struct_variants,json=structVariants,proto3" json:"struct_variants,omitempty"`
}

func (x *StructVariantList) Reset() {
	*x = StructVariantList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructVariantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructVariantList) ProtoMessage() {}

func (x *StructVariantList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructVariantList.ProtoReflect.Descriptor instead.
func (*StructVariantList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{4}
}

func (x *StructVariantList) GetStructVariants() []*StructVariantValue {
	if x != nil {
		return x.StructVariants
	}
	return nil
}

type Int32List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ints []int32 `protobuf:"fixed32,1,rep,packed,name=ints,proto3" json:"ints,omitempty"`
}

func (x *Int32List) Reset() {
	*x = Int32List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32List) ProtoMessage() {}

func (x *Int32List) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32List.ProtoReflect.Descriptor instead.
func (*Int32List) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{5}
}

func (x *Int32List) GetInts() []int32 {
	if x != nil {
		return x.Ints
	}
	return nil
}

type Float32List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Floats []float32 `protobuf:"fixed32,1,rep,packed,name=floats,proto3" json:"floats,omitempty"`
}

func (x *Float32List) Reset() {
	*x = Float32List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float32List) ProtoMessage() {}

func (x *Float32List) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float32List.ProtoReflect.Descriptor instead.
func (*Float32List) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{6}
}

func (x *Float32List) GetFloats() []float32 {
	if x != nil {
		return x.Floats
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strings []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{7}
}

func (x *StringList) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

// Structured object comprising named fields that map to dynamically typed values
type StructValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{8}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{9}
}

type StructList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StructValues []*StructValue `protobuf:"bytes,1,rep,name=struct_values,json=structValues,proto3" json:"struct_values,omitempty"`
}

func (x *StructList) Reset() {
	*x = StructList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructList) ProtoMessage() {}

func (x *StructList) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructList.ProtoReflect.Descriptor instead.
func (*StructList) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{10}
}

func (x *StructList) GetStructValues() []*StructValue {
	if x != nil {
		return x.StructValues
	}
	return nil
}

// Represents a dynamically typed value with straightforward mapping to
// OGP/JSON.
// Note that sfixed32 types are used to prefer marshalling performance
// to wire size.
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*Value_UndefinedValue
	//	*Value_EmptyValue
	//	*Value_Int32Value
	//	*Value_Float32Value
	//	*Value_StringValue
	//	*Value_StructValue
	//	*Value_Int32ArrayValues
	//	*Value_Float32ArrayValues
	//	*Value_StringArrayValues
	//	*Value_StructArrayValues
	//	*Value_DataPayload
	//	*Value_StructVariantValue
	//	*Value_StructVariantArrayValues
	Kind isValue_Kind `protobuf_oneof:"kind"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{11}
}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *Value) GetUndefinedValue() UndefinedValue {
	if x, ok := x.GetKind().(*Value_UndefinedValue); ok {
		return x.UndefinedValue
	}
	return UndefinedValue_UNDEFINED_VALUE
}

func (x *Value) GetEmptyValue() *Empty {
	if x, ok := x.GetKind().(*Value_EmptyValue); ok {
		return x.EmptyValue
	}
	return nil
}

func (x *Value) GetInt32Value() int32 {
	if x, ok := x.GetKind().(*Value_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (x *Value) GetFloat32Value() float32 {
	if x, ok := x.GetKind().(*Value_Float32Value); ok {
		return x.Float32Value
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x, ok := x.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Value) GetStructValue() *StructValue {
	if x, ok := x.GetKind().(*Value_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (x *Value) GetInt32ArrayValues() *Int32List {
	if x, ok := x.GetKind().(*Value_Int32ArrayValues); ok {
		return x.Int32ArrayValues
	}
	return nil
}

func (x *Value) GetFloat32ArrayValues() *Float32List {
	if x, ok := x.GetKind().(*Value_Float32ArrayValues); ok {
		return x.Float32ArrayValues
	}
	return nil
}

func (x *Value) GetStringArrayValues() *StringList {
	if x, ok := x.GetKind().(*Value_StringArrayValues); ok {
		return x.StringArrayValues
	}
	return nil
}

func (x *Value) GetStructArrayValues() *StructList {
	if x, ok := x.GetKind().(*Value_StructArrayValues); ok {
		return x.StructArrayValues
	}
	return nil
}

func (x *Value) GetDataPayload() *DataPayload {
	if x, ok := x.GetKind().(*Value_DataPayload); ok {
		return x.DataPayload
	}
	return nil
}

func (x *Value) GetStructVariantValue() *StructVariantValue {
	if x, ok := x.GetKind().(*Value_StructVariantValue); ok {
		return x.StructVariantValue
	}
	return nil
}

func (x *Value) GetStructVariantArrayValues() *StructVariantList {
	if x, ok := x.GetKind().(*Value_StructVariantArrayValues); ok {
		return x.StructVariantArrayValues
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_UndefinedValue struct {
	UndefinedValue UndefinedValue `protobuf:"varint,1,opt,name=undefined_value,json=undefinedValue,proto3,enum=st2138.UndefinedValue,oneof"`
}

type Value_EmptyValue struct {
	EmptyValue *Empty `protobuf:"bytes,2,opt,name=empty_value,json=emptyValue,proto3,oneof"` // Used for zero-argument commands
}

type Value_Int32Value struct {
	Int32Value int32 `protobuf:"fixed32,3,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Value_Float32Value struct {
	Float32Value float32 `protobuf:"fixed32,4,opt,name=float32_value,json=float32Value,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,6,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type Value_Int32ArrayValues struct {
	Int32ArrayValues *Int32List `protobuf:"bytes,7,opt,name=int32_array_values,json=int32ArrayValues,proto3,oneof"`
}

type Value_Float32ArrayValues struct {
	Float32ArrayValues *Float32List `protobuf:"bytes,8,opt,name=float32_array_values,json=float32ArrayValues,proto3,oneof"`
}

type Value_StringArrayValues struct {
	StringArrayValues *StringList `protobuf:"bytes,9,opt,name=string_array_values,json=stringArrayValues,proto3,oneof"`
}

type Value_StructArrayValues struct {
	StructArrayValues *StructList `protobuf:"bytes,10,opt,name=struct_array_values,json=structArrayValues,proto3,oneof"`
}

type Value_DataPayload struct {
	DataPayload *DataPayload `protobuf:"bytes,11,opt,name=data_payload,json=dataPayload,proto3,oneof"` // Used for commands that accept or return data blobs
}

type Value_StructVariantValue struct {
	StructVariantValue *StructVariantValue `protobuf:"bytes,12,opt,name=struct_variant_value,json=structVariantValue,proto3,oneof"`
}

type Value_StructVariantArrayValues struct {
	StructVariantArrayValues *StructVariantList `protobuf:"bytes,13,opt,name=struct_variant_array_values,json=structVariantArrayValues,proto3,oneof"`
}

func (*Value_UndefinedValue) isValue_Kind() {}

func (*Value_EmptyValue) isValue_Kind() {}

func (*Value_Int32Value) isValue_Kind() {}

func (*Value_Float32Value) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

func (*Value_Int32ArrayValues) isValue_Kind() {}

func (*Value_Float32ArrayValues) isValue_Kind() {}

func (*Value_StringArrayValues) isValue_Kind() {}

func (*Value_StructArrayValues) isValue_Kind() {}

func (*Value_DataPayload) isValue_Kind() {}

func (*Value_StructVariantValue) isValue_Kind() {}

func (*Value_StructVariantArrayValues) isValue_Kind() {}

type Import struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"` // SHA256 digest of the import file
}

func (x *Import) Reset() {
	*x = Import{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{12}
}

func (x *Import) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Import) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type GetParamPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	Oid  string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`    // Uniquely identifies the param at device scope
}

func (x *GetParamPayload) Reset() {
	*x = GetParamPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamPayload) ProtoMessage() {}

func (x *GetParamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamPayload.ProtoReflect.Descriptor instead.
func (*GetParamPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{13}
}

func (x *GetParamPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetParamPayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type ParamInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info        *ParamInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ArrayLength uint32     `protobuf:"varint,2,opt,name=array_length,json=arrayLength,proto3" json:"array_length,omitempty"` // If this ParamInfoResponse is for an array parameter, include the length of the array
}

func (x *ParamInfoResponse) Reset() {
	*x = ParamInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfoResponse) ProtoMessage() {}

func (x *ParamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfoResponse.ProtoReflect.Descriptor instead.
func (*ParamInfoResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{14}
}

func (x *ParamInfoResponse) GetInfo() *ParamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ParamInfoResponse) GetArrayLength() uint32 {
	if x != nil {
		return x.ArrayLength
	}
	return 0
}

// Specifies the OID and potentially its subtree of
// child parameters if the recursive flag is set.
type ParamInfoRequestPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	// Uniquely identifies starting parameter relative to device.params
	// Specifying "" selects all top-level parameters.
	OidPrefix string `protobuf:"bytes,2,opt,name=oid_prefix,json=oidPrefix,proto3" json:"oid_prefix,omitempty"`
	// Selects whether the param's child parameters should also be returned.
	Recursive bool `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *ParamInfoRequestPayload) Reset() {
	*x = ParamInfoRequestPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamInfoRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamInfoRequestPayload) ProtoMessage() {}

func (x *ParamInfoRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamInfoRequestPayload.ProtoReflect.Descriptor instead.
func (*ParamInfoRequestPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{15}
}

func (x *ParamInfoRequestPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ParamInfoRequestPayload) GetOidPrefix() string {
	if x != nil {
		return x.OidPrefix
	}
	return ""
}

func (x *ParamInfoRequestPayload) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type SetValuePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid   string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`     // Uniquely identifies the param at device scope
	Value *Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // The value to apply
}

func (x *SetValuePayload) Reset() {
	*x = SetValuePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValuePayload) ProtoMessage() {}

func (x *SetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValuePayload.ProtoReflect.Descriptor instead.
func (*SetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{16}
}

func (x *SetValuePayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *SetValuePayload) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SingleSetValuePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot  uint32           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`  // Uniquely identifies the device at node scope.
	Value *SetValuePayload `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // The param oid and value to apply
}

func (x *SingleSetValuePayload) Reset() {
	*x = SingleSetValuePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleSetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSetValuePayload) ProtoMessage() {}

func (x *SingleSetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSetValuePayload.ProtoReflect.Descriptor instead.
func (*SingleSetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{17}
}

func (x *SingleSetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SingleSetValuePayload) GetValue() *SetValuePayload {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetValuePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"` // Uniquely identifies the device at node scope.
	Oid  string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`    // Uniquely identifies the param at device scope
}

func (x *GetValuePayload) Reset() {
	*x = GetValuePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValuePayload) ProtoMessage() {}

func (x *GetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValuePayload.ProtoReflect.Descriptor instead.
func (*GetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{18}
}

func (x *GetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *GetValuePayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

type MultiSetValuePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot   uint32             `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`    // Uniquely identifies the device at node scope.
	Values []*SetValuePayload `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"` // The param oids and values to apply
}

func (x *MultiSetValuePayload) Reset() {
	*x = MultiSetValuePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSetValuePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSetValuePayload) ProtoMessage() {}

func (x *MultiSetValuePayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSetValuePayload.ProtoReflect.Descriptor instead.
func (*MultiSetValuePayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{19}
}

func (x *MultiSetValuePayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *MultiSetValuePayload) GetValues() []*SetValuePayload {
	if x != nil {
		return x.Values
	}
	return nil
}

type UpdateSubscriptionsPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot        uint32   `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                 // Uniquely identifies the device at node scope.
	AddedOids   []string `protobuf:"bytes,2,rep,name=added_oids,json=addedOids,proto3" json:"added_oids,omitempty"`       // A list of object IDs to add to current subscriptions (or a partial OID with a trailing "*" to indicate all object IDs with the same prefix)
	RemovedOids []string `protobuf:"bytes,3,rep,name=removed_oids,json=removedOids,proto3" json:"removed_oids,omitempty"` // A list of object IDs to remove from current subscriptions (or a partial OID with a trailing "*" to indicate all object IDs with the same prefix)
}

func (x *UpdateSubscriptionsPayload) Reset() {
	*x = UpdateSubscriptionsPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSubscriptionsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionsPayload) ProtoMessage() {}

func (x *UpdateSubscriptionsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionsPayload.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionsPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateSubscriptionsPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *UpdateSubscriptionsPayload) GetAddedOids() []string {
	if x != nil {
		return x.AddedOids
	}
	return nil
}

func (x *UpdateSubscriptionsPayload) GetRemovedOids() []string {
	if x != nil {
		return x.RemovedOids
	}
	return nil
}

// Defines a command for a device.
// Commands provide a way to use device connection to execute commands from other devices.
// Superseded by just adding a `respond` field to the Param message.
//
//	message Command {
//	  Param definition = 1; // provides command's input values
//	  bool respond = 2;     // true when the device will respond to the command, false otherwise.
//	}
//
// When streamed, only the value field will be used after the first message.
//
// The proceed flag allows the client to indicate to the server that is has already recieved a payload
// Ex. If a command streams a large file, the client can set proceed to false to indicate to the server
// that it does not need the rest of the file.
type ExecuteCommandPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot    uint32 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`       // Slot id of the device
	Oid     string `protobuf:"bytes,2,opt,name=oid,proto3" json:"oid,omitempty"`          // The object id of the command to execute relative to device.commands
	Value   *Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`      // The command's parameter value, if any
	Respond bool   `protobuf:"varint,4,opt,name=respond,proto3" json:"respond,omitempty"` // False if client wants to surpress response from server
}

func (x *ExecuteCommandPayload) Reset() {
	*x = ExecuteCommandPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteCommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandPayload) ProtoMessage() {}

func (x *ExecuteCommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandPayload.ProtoReflect.Descriptor instead.
func (*ExecuteCommandPayload) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteCommandPayload) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ExecuteCommandPayload) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *ExecuteCommandPayload) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ExecuteCommandPayload) GetRespond() bool {
	if x != nil {
		return x.Respond
	}
	return false
}

type Exception struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ErrorMessage *PolyglotText `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Details      string        `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *Exception) Reset() {
	*x = Exception{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Exception) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exception) ProtoMessage() {}

func (x *Exception) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exception.ProtoReflect.Descriptor instead.
func (*Exception) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{22}
}

func (x *Exception) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exception) GetErrorMessage() *PolyglotText {
	if x != nil {
		return x.ErrorMessage
	}
	return nil
}

func (x *Exception) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// When streamed, only the response field will be used after the first message.
type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Kind:
	//
	//	*CommandResponse_NoResponse
	//	*CommandResponse_Response
	//	*CommandResponse_Exception
	Kind isCommandResponse_Kind `protobuf_oneof:"kind"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{23}
}

func (m *CommandResponse) GetKind() isCommandResponse_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *CommandResponse) GetNoResponse() *Empty {
	if x, ok := x.GetKind().(*CommandResponse_NoResponse); ok {
		return x.NoResponse
	}
	return nil
}

func (x *CommandResponse) GetResponse() *Value {
	if x, ok := x.GetKind().(*CommandResponse_Response); ok {
		return x.Response
	}
	return nil
}

func (x *CommandResponse) GetException() *Exception {
	if x, ok := x.GetKind().(*CommandResponse_Exception); ok {
		return x.Exception
	}
	return nil
}

type isCommandResponse_Kind interface {
	isCommandResponse_Kind()
}

type CommandResponse_NoResponse struct {
	NoResponse *Empty `protobuf:"bytes,1,opt,name=no_response,json=noResponse,proto3,oneof"` // Server/Device does not have a response for the command.
}

type CommandResponse_Response struct {
	Response *Value `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type CommandResponse_Exception struct {
	Exception *Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"` // This is for Server/Device error executing the command.
}

func (*CommandResponse_NoResponse) isCommandResponse_Kind() {}

func (*CommandResponse_Response) isCommandResponse_Kind() {}

func (*CommandResponse_Exception) isCommandResponse_Kind() {}

var File_param_proto protoreflect.FileDescriptor

var file_param_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x1a, 0x0e, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x69, 0x64, 0x22, 0xe5, 0x02, 0x0a, 0x0b,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3d, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x12, 0x4e, 0x0a, 0x10, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x3a, 0x0a, 0x0f, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x5a, 0x49, 0x50, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x44, 0x45, 0x46, 0x4c, 0x41, 0x54, 0x45, 0x10, 0x02, 0x42, 0x06, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x22, 0xda, 0x06, 0x0a, 0x05, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x28, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74,
	0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78,
	0x74, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x32,
	0x31, 0x33, 0x38, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12,
	0x41, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x69, 0x6e, 0x74, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x69, 0x6e,
	0x74, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6c, 0x6f,
	0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74,
	0x32, 0x31, 0x33, 0x38, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x69, 0x64, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x65, 0x73, 0x18, 0x11, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x69, 0x64, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f,
	0x73, 0x65, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6c, 0x65,
	0x73, 0x73, 0x18, 0x13, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6c,
	0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f,
	0x6f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4f, 0x69, 0x64, 0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x48, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x48, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x69, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x58, 0x0a, 0x11, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x43, 0x0a, 0x0f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x32, 0x31,
	0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x1f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0f,
	0x52, 0x04, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33,
	0x32, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x73, 0x22, 0x26, 0x0a,
	0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x48,
	0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x46, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x38, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xab, 0x06, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x41, 0x0a, 0x0f, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x75, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x74,
	0x32, 0x31, 0x33, 0x38, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33,
	0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0f, 0x48, 0x00, 0x52,
	0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x41, 0x0a, 0x12, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x10, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x14, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x5f,
	0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x12, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x33, 0x32, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x44, 0x0a,
	0x13, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x32,
	0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x11, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x13, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x11, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x4e, 0x0a, 0x14, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52,
	0x12, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x5a, 0x0a, 0x1b, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33,
	0x38, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x18, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42,
	0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x32, 0x0a, 0x06, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6f, 0x69, 0x64, 0x22, 0x5d, 0x0a, 0x11, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38,
	0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x61, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x61, 0x79, 0x4c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x22, 0x6a, 0x0a, 0x17, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x69, 0x64, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22,
	0x48, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6f, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x15, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x22, 0x5b,
	0x0a, 0x14, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x32,
	0x31, 0x33, 0x38, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x6f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4f, 0x69, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x6f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x4f, 0x69, 0x64, 0x73, 0x22,
	0x7c, 0x0a, 0x15, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x74, 0x0a,
	0x09, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6c, 0x6f, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x0c, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x6e, 0x6f, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73,
	0x74, 0x32, 0x31, 0x33, 0x38, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x6e,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x74,
	0x32, 0x31, 0x33, 0x38, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x32, 0x31,
	0x33, 0x38, 0x2e, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09,
	0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x2a, 0xe1, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54,
	0x33, 0x32, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x10,
	0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x0a, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x52,
	0x55, 0x43, 0x54, 0x5f, 0x56, 0x41, 0x52, 0x49, 0x41, 0x4e, 0x54, 0x10, 0x0b, 0x12, 0x0f, 0x0a,
	0x0b, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x0e, 0x12, 0x11,
	0x0a, 0x0d, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10,
	0x10, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x52, 0x52, 0x41,
	0x59, 0x10, 0x11, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x12, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10,
	0x20, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x5f, 0x56, 0x41, 0x52, 0x49,
	0x41, 0x4e, 0x54, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x21, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x41, 0x54, 0x41, 0x10, 0x32, 0x2a, 0x25, 0x0a, 0x0e, 0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x44, 0x45, 0x46,
	0x49, 0x4e, 0x45, 0x44, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x42, 0x28, 0x0a, 0x15,
	0x63, 0x61, 0x74, 0x65, 0x6e, 0x61, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x42, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x48, 0x01, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_param_proto_rawDescOnce sync.Once
	file_param_proto_rawDescData = file_param_proto_rawDesc
)

func file_param_proto_rawDescGZIP() []byte {
	file_param_proto_rawDescOnce.Do(func() {
		file_param_proto_rawDescData = protoimpl.X.CompressGZIP(file_param_proto_rawDescData)
	})
	return file_param_proto_rawDescData
}

var file_param_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_param_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_param_proto_goTypes = []interface{}{
	(ParamType)(0),                     // 0: st2138.ParamType
	(UndefinedValue)(0),                // 1: st2138.UndefinedValue
	(DataPayload_PayloadEncoding)(0),   // 2: st2138.DataPayload.PayloadEncoding
	(*ParamInfo)(nil),                  // 3: st2138.ParamInfo
	(*DataPayload)(nil),                // 4: st2138.DataPayload
	(*Param)(nil),                      // 5: st2138.Param
	(*StructVariantValue)(nil),         // 6: st2138.StructVariantValue
	(*StructVariantList)(nil),          // 7: st2138.StructVariantList
	(*Int32List)(nil),                  // 8: st2138.Int32List
	(*Float32List)(nil),                // 9: st2138.Float32List
	(*StringList)(nil),                 // 10: st2138.StringList
	(*StructValue)(nil),                // 11: st2138.StructValue
	(*Empty)(nil),                      // 12: st2138.Empty
	(*StructList)(nil),                 // 13: st2138.StructList
	(*Value)(nil),                      // 14: st2138.Value
	(*Import)(nil),                     // 15: st2138.Import
	(*GetParamPayload)(nil),            // 16: st2138.GetParamPayload
	(*ParamInfoResponse)(nil),          // 17: st2138.ParamInfoResponse
	(*ParamInfoRequestPayload)(nil),    // 18: st2138.ParamInfoRequestPayload
	(*SetValuePayload)(nil),            // 19: st2138.SetValuePayload
	(*SingleSetValuePayload)(nil),      // 20: st2138.SingleSetValuePayload
	(*GetValuePayload)(nil),            // 21: st2138.GetValuePayload
	(*MultiSetValuePayload)(nil),       // 22: st2138.MultiSetValuePayload
	(*UpdateSubscriptionsPayload)(nil), // 23: st2138.UpdateSubscriptionsPayload
	(*ExecuteCommandPayload)(nil),      // 24: st2138.ExecuteCommandPayload
	(*Exception)(nil),                  // 25: st2138.Exception
	(*CommandResponse)(nil),            // 26: st2138.CommandResponse
	nil,                                // 27: st2138.DataPayload.MetadataEntry
	nil,                                // 28: st2138.Param.ClientHintsEntry
	nil,                                // 29: st2138.Param.ParamsEntry
	nil,                                // 30: st2138.StructValue.FieldsEntry
	(*PolyglotText)(nil),               // 31: st2138.PolyglotText
	(*Constraint)(nil),                 // 32: st2138.Constraint
}
var file_param_proto_depIdxs = []int32{
	31, // 0: st2138.ParamInfo.name:type_name -> st2138.PolyglotText
	0,  // 1: st2138.ParamInfo.type:type_name -> st2138.ParamType
	27, // 2: st2138.DataPayload.metadata:type_name -> st2138.DataPayload.MetadataEntry
	2,  // 3: st2138.DataPayload.payload_encoding:type_name -> st2138.DataPayload.PayloadEncoding
	31, // 4: st2138.Param.name:type_name -> st2138.PolyglotText
	0,  // 5: st2138.Param.type:type_name -> st2138.ParamType
	14, // 6: st2138.Param.value:type_name -> st2138.Value
	32, // 7: st2138.Param.constraint:type_name -> st2138.Constraint
	28, // 8: st2138.Param.client_hints:type_name -> st2138.Param.ClientHintsEntry
	29, // 9: st2138.Param.params:type_name -> st2138.Param.ParamsEntry
	31, // 10: st2138.Param.help:type_name -> st2138.PolyglotText
	15, // 11: st2138.Param.import:type_name -> st2138.Import
	14, // 12: st2138.StructVariantValue.value:type_name -> st2138.Value
	6,  // 13: st2138.StructVariantList.struct_variants:type_name -> st2138.StructVariantValue
	30, // 14: st2138.StructValue.fields:type_name -> st2138.StructValue.FieldsEntry
	11, // 15: st2138.StructList.struct_values:type_name -> st2138.StructValue
	1,  // 16: st2138.Value.undefined_value:type_name -> st2138.UndefinedValue
	12, // 17: st2138.Value.empty_value:type_name -> st2138.Empty
	11, // 18: st2138.Value.struct_value:type_name -> st2138.StructValue
	8,  // 19: st2138.Value.int32_array_values:type_name -> st2138.Int32List
	9,  // 20: st2138.Value.float32_array_values:type_name -> st2138.Float32List
	10, // 21: st2138.Value.string_array_values:type_name -> st2138.StringList
	13, // 22: st2138.Value.struct_array_values:type_name -> st2138.StructList
	4,  // 23: st2138.Value.data_payload:type_name -> st2138.DataPayload
	6,  // 24: st2138.Value.struct_variant_value:type_name -> st2138.StructVariantValue
	7,  // 25: st2138.Value.struct_variant_array_values:type_name -> st2138.StructVariantList
	3,  // 26: st2138.ParamInfoResponse.info:type_name -> st2138.ParamInfo
	14, // 27: st2138.SetValuePayload.value:type_name -> st2138.Value
	19, // 28: st2138.SingleSetValuePayload.value:type_name -> st2138.SetValuePayload
	19, // 29: st2138.MultiSetValuePayload.values:type_name -> st2138.SetValuePayload
	14, // 30: st2138.ExecuteCommandPayload.value:type_name -> st2138.Value
	31, // 31: st2138.Exception.error_message:type_name -> st2138.PolyglotText
	12, // 32: st2138.CommandResponse.no_response:type_name -> st2138.Empty
	14, // 33: st2138.CommandResponse.response:type_name -> st2138.Value
	25, // 34: st2138.CommandResponse.exception:type_name -> st2138.Exception
	5,  // 35: st2138.Param.ParamsEntry.value:type_name -> st2138.Param
	14, // 36: st2138.StructValue.FieldsEntry.value:type_name -> st2138.Value
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_param_proto_init() }
func file_param_proto_init() {
	if File_param_proto != nil {
		return
	}
	file_language_proto_init()
	file_constraint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_param_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructVariantValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructVariantList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Float32List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Import); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamInfoRequestPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValuePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleSetValuePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValuePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiSetValuePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSubscriptionsPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteCommandPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Exception); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_param_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*DataPayload_Url)(nil),
		(*DataPayload_Payload)(nil),
	}
	file_param_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*Value_UndefinedValue)(nil),
		(*Value_EmptyValue)(nil),
		(*Value_Int32Value)(nil),
		(*Value_Float32Value)(nil),
		(*Value_StringValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_Int32ArrayValues)(nil),
		(*Value_Float32ArrayValues)(nil),
		(*Value_StringArrayValues)(nil),
		(*Value_StructArrayValues)(nil),
		(*Value_DataPayload)(nil),
		(*Value_StructVariantValue)(nil),
		(*Value_StructVariantArrayValues)(nil),
	}
	file_param_proto_msgTypes[23].OneofWrappers = []interface{}{
		(*CommandResponse_NoResponse)(nil),
		(*CommandResponse_Response)(nil),
		(*CommandResponse_Exception)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_param_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_param_proto_goTypes,
		DependencyIndexes: file_param_proto_depIdxs,
		EnumInfos:         file_param_proto_enumTypes,
		MessageInfos:      file_param_proto_msgTypes,
	}.Build()
	File_param_proto = out.File
	file_param_proto_rawDesc = nil
	file_param_proto_goTypes = nil
	file_param_proto_depIdxs = nil
}
