//
// Copyright (c) by the Society of Motion Picture and Television Engineers
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
// may be used to endorse or promote products derived from this software without
// specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: service.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CatenaService_DeviceRequest_FullMethodName         = "/st2138.CatenaService/DeviceRequest"
	CatenaService_GetPopulatedSlots_FullMethodName     = "/st2138.CatenaService/GetPopulatedSlots"
	CatenaService_ExecuteCommand_FullMethodName        = "/st2138.CatenaService/ExecuteCommand"
	CatenaService_ExternalObjectRequest_FullMethodName = "/st2138.CatenaService/ExternalObjectRequest"
	CatenaService_ParamInfoRequest_FullMethodName      = "/st2138.CatenaService/ParamInfoRequest"
	CatenaService_SetValue_FullMethodName              = "/st2138.CatenaService/SetValue"
	CatenaService_GetValue_FullMethodName              = "/st2138.CatenaService/GetValue"
	CatenaService_MultiSetValue_FullMethodName         = "/st2138.CatenaService/MultiSetValue"
	CatenaService_UpdateSubscriptions_FullMethodName   = "/st2138.CatenaService/UpdateSubscriptions"
	CatenaService_GetParam_FullMethodName              = "/st2138.CatenaService/GetParam"
	CatenaService_Connect_FullMethodName               = "/st2138.CatenaService/Connect"
	CatenaService_AddLanguage_FullMethodName           = "/st2138.CatenaService/AddLanguage"
	CatenaService_LanguagePackRequest_FullMethodName   = "/st2138.CatenaService/LanguagePackRequest"
	CatenaService_ListLanguages_FullMethodName         = "/st2138.CatenaService/ListLanguages"
	CatenaService_RefreshToken_FullMethodName          = "/st2138.CatenaService/RefreshToken"
	CatenaService_RevokeAccess_FullMethodName          = "/st2138.CatenaService/RevokeAccess"
)

// CatenaServiceClient is the client API for CatenaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatenaServiceClient interface {
	DeviceRequest(ctx context.Context, in *DeviceRequestPayload, opts ...grpc.CallOption) (CatenaService_DeviceRequestClient, error)
	GetPopulatedSlots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlotList, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandPayload, opts ...grpc.CallOption) (CatenaService_ExecuteCommandClient, error)
	ExternalObjectRequest(ctx context.Context, in *ExternalObjectRequestPayload, opts ...grpc.CallOption) (CatenaService_ExternalObjectRequestClient, error)
	ParamInfoRequest(ctx context.Context, in *ParamInfoRequestPayload, opts ...grpc.CallOption) (CatenaService_ParamInfoRequestClient, error)
	SetValue(ctx context.Context, in *SingleSetValuePayload, opts ...grpc.CallOption) (*Empty, error)
	GetValue(ctx context.Context, in *GetValuePayload, opts ...grpc.CallOption) (*Value, error)
	MultiSetValue(ctx context.Context, in *MultiSetValuePayload, opts ...grpc.CallOption) (*Empty, error)
	UpdateSubscriptions(ctx context.Context, in *UpdateSubscriptionsPayload, opts ...grpc.CallOption) (CatenaService_UpdateSubscriptionsClient, error)
	GetParam(ctx context.Context, in *GetParamPayload, opts ...grpc.CallOption) (*DeviceComponent_ComponentParam, error)
	// The stream of PushUpdates is open-ended, terminating only when the
	// logical connection with the client is terminated.
	// Connected clients should use the RefreshToken RPC to prevent the
	// connection from being terminated on token expiry.
	Connect(ctx context.Context, in *ConnectPayload, opts ...grpc.CallOption) (CatenaService_ConnectClient, error)
	// Multi-language support
	AddLanguage(ctx context.Context, in *AddLanguagePayload, opts ...grpc.CallOption) (*Empty, error)
	LanguagePackRequest(ctx context.Context, in *LanguagePackRequestPayload, opts ...grpc.CallOption) (*DeviceComponent_ComponentLanguagePack, error)
	ListLanguages(ctx context.Context, in *Slot, opts ...grpc.CallOption) (*LanguageList, error)
	// Token management RPCs
	RefreshToken(ctx context.Context, in *RefreshTokenPayload, opts ...grpc.CallOption) (*ConnectionStatus, error)
	RevokeAccess(ctx context.Context, in *RevokeAccessPayload, opts ...grpc.CallOption) (*RevocationResponse, error)
}

type catenaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatenaServiceClient(cc grpc.ClientConnInterface) CatenaServiceClient {
	return &catenaServiceClient{cc}
}

func (c *catenaServiceClient) DeviceRequest(ctx context.Context, in *DeviceRequestPayload, opts ...grpc.CallOption) (CatenaService_DeviceRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[0], CatenaService_DeviceRequest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceDeviceRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_DeviceRequestClient interface {
	Recv() (*DeviceComponent, error)
	grpc.ClientStream
}

type catenaServiceDeviceRequestClient struct {
	grpc.ClientStream
}

func (x *catenaServiceDeviceRequestClient) Recv() (*DeviceComponent, error) {
	m := new(DeviceComponent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) GetPopulatedSlots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SlotList, error) {
	out := new(SlotList)
	err := c.cc.Invoke(ctx, CatenaService_GetPopulatedSlots_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandPayload, opts ...grpc.CallOption) (CatenaService_ExecuteCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[1], CatenaService_ExecuteCommand_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceExecuteCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_ExecuteCommandClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type catenaServiceExecuteCommandClient struct {
	grpc.ClientStream
}

func (x *catenaServiceExecuteCommandClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) ExternalObjectRequest(ctx context.Context, in *ExternalObjectRequestPayload, opts ...grpc.CallOption) (CatenaService_ExternalObjectRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[2], CatenaService_ExternalObjectRequest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceExternalObjectRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_ExternalObjectRequestClient interface {
	Recv() (*ExternalObjectPayload, error)
	grpc.ClientStream
}

type catenaServiceExternalObjectRequestClient struct {
	grpc.ClientStream
}

func (x *catenaServiceExternalObjectRequestClient) Recv() (*ExternalObjectPayload, error) {
	m := new(ExternalObjectPayload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) ParamInfoRequest(ctx context.Context, in *ParamInfoRequestPayload, opts ...grpc.CallOption) (CatenaService_ParamInfoRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[3], CatenaService_ParamInfoRequest_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceParamInfoRequestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_ParamInfoRequestClient interface {
	Recv() (*ParamInfoResponse, error)
	grpc.ClientStream
}

type catenaServiceParamInfoRequestClient struct {
	grpc.ClientStream
}

func (x *catenaServiceParamInfoRequestClient) Recv() (*ParamInfoResponse, error) {
	m := new(ParamInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) SetValue(ctx context.Context, in *SingleSetValuePayload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CatenaService_SetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) GetValue(ctx context.Context, in *GetValuePayload, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, CatenaService_GetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) MultiSetValue(ctx context.Context, in *MultiSetValuePayload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CatenaService_MultiSetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) UpdateSubscriptions(ctx context.Context, in *UpdateSubscriptionsPayload, opts ...grpc.CallOption) (CatenaService_UpdateSubscriptionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[4], CatenaService_UpdateSubscriptions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceUpdateSubscriptionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_UpdateSubscriptionsClient interface {
	Recv() (*DeviceComponent_ComponentParam, error)
	grpc.ClientStream
}

type catenaServiceUpdateSubscriptionsClient struct {
	grpc.ClientStream
}

func (x *catenaServiceUpdateSubscriptionsClient) Recv() (*DeviceComponent_ComponentParam, error) {
	m := new(DeviceComponent_ComponentParam)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) GetParam(ctx context.Context, in *GetParamPayload, opts ...grpc.CallOption) (*DeviceComponent_ComponentParam, error) {
	out := new(DeviceComponent_ComponentParam)
	err := c.cc.Invoke(ctx, CatenaService_GetParam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) Connect(ctx context.Context, in *ConnectPayload, opts ...grpc.CallOption) (CatenaService_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &CatenaService_ServiceDesc.Streams[5], CatenaService_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &catenaServiceConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatenaService_ConnectClient interface {
	Recv() (*PushUpdates, error)
	grpc.ClientStream
}

type catenaServiceConnectClient struct {
	grpc.ClientStream
}

func (x *catenaServiceConnectClient) Recv() (*PushUpdates, error) {
	m := new(PushUpdates)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catenaServiceClient) AddLanguage(ctx context.Context, in *AddLanguagePayload, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, CatenaService_AddLanguage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) LanguagePackRequest(ctx context.Context, in *LanguagePackRequestPayload, opts ...grpc.CallOption) (*DeviceComponent_ComponentLanguagePack, error) {
	out := new(DeviceComponent_ComponentLanguagePack)
	err := c.cc.Invoke(ctx, CatenaService_LanguagePackRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) ListLanguages(ctx context.Context, in *Slot, opts ...grpc.CallOption) (*LanguageList, error) {
	out := new(LanguageList)
	err := c.cc.Invoke(ctx, CatenaService_ListLanguages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenPayload, opts ...grpc.CallOption) (*ConnectionStatus, error) {
	out := new(ConnectionStatus)
	err := c.cc.Invoke(ctx, CatenaService_RefreshToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catenaServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessPayload, opts ...grpc.CallOption) (*RevocationResponse, error) {
	out := new(RevocationResponse)
	err := c.cc.Invoke(ctx, CatenaService_RevokeAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatenaServiceServer is the server API for CatenaService service.
// All implementations must embed UnimplementedCatenaServiceServer
// for forward compatibility
type CatenaServiceServer interface {
	DeviceRequest(*DeviceRequestPayload, CatenaService_DeviceRequestServer) error
	GetPopulatedSlots(context.Context, *Empty) (*SlotList, error)
	ExecuteCommand(*ExecuteCommandPayload, CatenaService_ExecuteCommandServer) error
	ExternalObjectRequest(*ExternalObjectRequestPayload, CatenaService_ExternalObjectRequestServer) error
	ParamInfoRequest(*ParamInfoRequestPayload, CatenaService_ParamInfoRequestServer) error
	SetValue(context.Context, *SingleSetValuePayload) (*Empty, error)
	GetValue(context.Context, *GetValuePayload) (*Value, error)
	MultiSetValue(context.Context, *MultiSetValuePayload) (*Empty, error)
	UpdateSubscriptions(*UpdateSubscriptionsPayload, CatenaService_UpdateSubscriptionsServer) error
	GetParam(context.Context, *GetParamPayload) (*DeviceComponent_ComponentParam, error)
	// The stream of PushUpdates is open-ended, terminating only when the
	// logical connection with the client is terminated.
	// Connected clients should use the RefreshToken RPC to prevent the
	// connection from being terminated on token expiry.
	Connect(*ConnectPayload, CatenaService_ConnectServer) error
	// Multi-language support
	AddLanguage(context.Context, *AddLanguagePayload) (*Empty, error)
	LanguagePackRequest(context.Context, *LanguagePackRequestPayload) (*DeviceComponent_ComponentLanguagePack, error)
	ListLanguages(context.Context, *Slot) (*LanguageList, error)
	// Token management RPCs
	RefreshToken(context.Context, *RefreshTokenPayload) (*ConnectionStatus, error)
	RevokeAccess(context.Context, *RevokeAccessPayload) (*RevocationResponse, error)
	mustEmbedUnimplementedCatenaServiceServer()
}

// UnimplementedCatenaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCatenaServiceServer struct {
}

func (UnimplementedCatenaServiceServer) DeviceRequest(*DeviceRequestPayload, CatenaService_DeviceRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method DeviceRequest not implemented")
}
func (UnimplementedCatenaServiceServer) GetPopulatedSlots(context.Context, *Empty) (*SlotList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopulatedSlots not implemented")
}
func (UnimplementedCatenaServiceServer) ExecuteCommand(*ExecuteCommandPayload, CatenaService_ExecuteCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCatenaServiceServer) ExternalObjectRequest(*ExternalObjectRequestPayload, CatenaService_ExternalObjectRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method ExternalObjectRequest not implemented")
}
func (UnimplementedCatenaServiceServer) ParamInfoRequest(*ParamInfoRequestPayload, CatenaService_ParamInfoRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method ParamInfoRequest not implemented")
}
func (UnimplementedCatenaServiceServer) SetValue(context.Context, *SingleSetValuePayload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedCatenaServiceServer) GetValue(context.Context, *GetValuePayload) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedCatenaServiceServer) MultiSetValue(context.Context, *MultiSetValuePayload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiSetValue not implemented")
}
func (UnimplementedCatenaServiceServer) UpdateSubscriptions(*UpdateSubscriptionsPayload, CatenaService_UpdateSubscriptionsServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateSubscriptions not implemented")
}
func (UnimplementedCatenaServiceServer) GetParam(context.Context, *GetParamPayload) (*DeviceComponent_ComponentParam, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParam not implemented")
}
func (UnimplementedCatenaServiceServer) Connect(*ConnectPayload, CatenaService_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCatenaServiceServer) AddLanguage(context.Context, *AddLanguagePayload) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLanguage not implemented")
}
func (UnimplementedCatenaServiceServer) LanguagePackRequest(context.Context, *LanguagePackRequestPayload) (*DeviceComponent_ComponentLanguagePack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LanguagePackRequest not implemented")
}
func (UnimplementedCatenaServiceServer) ListLanguages(context.Context, *Slot) (*LanguageList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLanguages not implemented")
}
func (UnimplementedCatenaServiceServer) RefreshToken(context.Context, *RefreshTokenPayload) (*ConnectionStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedCatenaServiceServer) RevokeAccess(context.Context, *RevokeAccessPayload) (*RevocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedCatenaServiceServer) mustEmbedUnimplementedCatenaServiceServer() {}

// UnsafeCatenaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatenaServiceServer will
// result in compilation errors.
type UnsafeCatenaServiceServer interface {
	mustEmbedUnimplementedCatenaServiceServer()
}

func RegisterCatenaServiceServer(s grpc.ServiceRegistrar, srv CatenaServiceServer) {
	s.RegisterService(&CatenaService_ServiceDesc, srv)
}

func _CatenaService_DeviceRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeviceRequestPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).DeviceRequest(m, &catenaServiceDeviceRequestServer{stream})
}

type CatenaService_DeviceRequestServer interface {
	Send(*DeviceComponent) error
	grpc.ServerStream
}

type catenaServiceDeviceRequestServer struct {
	grpc.ServerStream
}

func (x *catenaServiceDeviceRequestServer) Send(m *DeviceComponent) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_GetPopulatedSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).GetPopulatedSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_GetPopulatedSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).GetPopulatedSlots(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_ExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCommandPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).ExecuteCommand(m, &catenaServiceExecuteCommandServer{stream})
}

type CatenaService_ExecuteCommandServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type catenaServiceExecuteCommandServer struct {
	grpc.ServerStream
}

func (x *catenaServiceExecuteCommandServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_ExternalObjectRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExternalObjectRequestPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).ExternalObjectRequest(m, &catenaServiceExternalObjectRequestServer{stream})
}

type CatenaService_ExternalObjectRequestServer interface {
	Send(*ExternalObjectPayload) error
	grpc.ServerStream
}

type catenaServiceExternalObjectRequestServer struct {
	grpc.ServerStream
}

func (x *catenaServiceExternalObjectRequestServer) Send(m *ExternalObjectPayload) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_ParamInfoRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ParamInfoRequestPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).ParamInfoRequest(m, &catenaServiceParamInfoRequestServer{stream})
}

type CatenaService_ParamInfoRequestServer interface {
	Send(*ParamInfoResponse) error
	grpc.ServerStream
}

type catenaServiceParamInfoRequestServer struct {
	grpc.ServerStream
}

func (x *catenaServiceParamInfoRequestServer) Send(m *ParamInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleSetValuePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).SetValue(ctx, req.(*SingleSetValuePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValuePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).GetValue(ctx, req.(*GetValuePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_MultiSetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiSetValuePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).MultiSetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_MultiSetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).MultiSetValue(ctx, req.(*MultiSetValuePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_UpdateSubscriptions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateSubscriptionsPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).UpdateSubscriptions(m, &catenaServiceUpdateSubscriptionsServer{stream})
}

type CatenaService_UpdateSubscriptionsServer interface {
	Send(*DeviceComponent_ComponentParam) error
	grpc.ServerStream
}

type catenaServiceUpdateSubscriptionsServer struct {
	grpc.ServerStream
}

func (x *catenaServiceUpdateSubscriptionsServer) Send(m *DeviceComponent_ComponentParam) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_GetParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParamPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).GetParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_GetParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).GetParam(ctx, req.(*GetParamPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectPayload)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatenaServiceServer).Connect(m, &catenaServiceConnectServer{stream})
}

type CatenaService_ConnectServer interface {
	Send(*PushUpdates) error
	grpc.ServerStream
}

type catenaServiceConnectServer struct {
	grpc.ServerStream
}

func (x *catenaServiceConnectServer) Send(m *PushUpdates) error {
	return x.ServerStream.SendMsg(m)
}

func _CatenaService_AddLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLanguagePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).AddLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_AddLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).AddLanguage(ctx, req.(*AddLanguagePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_LanguagePackRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanguagePackRequestPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).LanguagePackRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_LanguagePackRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).LanguagePackRequest(ctx, req.(*LanguagePackRequestPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_ListLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Slot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).ListLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_ListLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).ListLanguages(ctx, req.(*Slot))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).RefreshToken(ctx, req.(*RefreshTokenPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatenaService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatenaServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatenaService_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatenaServiceServer).RevokeAccess(ctx, req.(*RevokeAccessPayload))
	}
	return interceptor(ctx, in, info, handler)
}

// CatenaService_ServiceDesc is the grpc.ServiceDesc for CatenaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatenaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "st2138.CatenaService",
	HandlerType: (*CatenaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopulatedSlots",
			Handler:    _CatenaService_GetPopulatedSlots_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _CatenaService_SetValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _CatenaService_GetValue_Handler,
		},
		{
			MethodName: "MultiSetValue",
			Handler:    _CatenaService_MultiSetValue_Handler,
		},
		{
			MethodName: "GetParam",
			Handler:    _CatenaService_GetParam_Handler,
		},
		{
			MethodName: "AddLanguage",
			Handler:    _CatenaService_AddLanguage_Handler,
		},
		{
			MethodName: "LanguagePackRequest",
			Handler:    _CatenaService_LanguagePackRequest_Handler,
		},
		{
			MethodName: "ListLanguages",
			Handler:    _CatenaService_ListLanguages_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _CatenaService_RefreshToken_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _CatenaService_RevokeAccess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeviceRequest",
			Handler:       _CatenaService_DeviceRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecuteCommand",
			Handler:       _CatenaService_ExecuteCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExternalObjectRequest",
			Handler:       _CatenaService_ExternalObjectRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ParamInfoRequest",
			Handler:       _CatenaService_ParamInfoRequest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateSubscriptions",
			Handler:       _CatenaService_UpdateSubscriptions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Connect",
			Handler:       _CatenaService_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
